# Generated by Django 3.2.12 on 2022-03-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jelentkezo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('tagozat', models.CharField(choices=[('A', 'Olasz'), ('B', 'Angol'), ('C', 'Matek-magyar'), ('D', 'Német-rajz'), ('E', 'Biosz-kémia'), ('F', 'Infó-média')], default='A', max_length=1)),
                ('pont', models.IntegerField()),
                ('felveve', models.BooleanField(default=False)),
            ],
        ),
    ]
