# Generated by Django 3.2.12 on 2022-03-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('felvetel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jelentkezo',
            options={'verbose_name': 'Jelentkező', 'verbose_name_plural': 'Jelentkezők'},
        ),
    ]
