# Generated by Django 3.2.12 on 2022-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felvetel', '0002_alter_jelentkezo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jelentkezo',
            name='azonosito',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
