# Generated by Django 4.0.3 on 2022-03-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felvetel', '0003_jelentkezo_azonosito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jelentkezo',
            old_name='tagozat',
            new_name='tagozat1',
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='tagozat2',
            field=models.CharField(blank=True, choices=[('A', 'Olasz'), ('B', 'Angol'), ('C', 'Matek-magyar'), ('D', 'Német-rajz'), ('E', 'Biosz-kémia'), ('F', 'Infó-média')], max_length=1),
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='tagozat3',
            field=models.CharField(blank=True, choices=[('A', 'Olasz'), ('B', 'Angol'), ('C', 'Matek-magyar'), ('D', 'Német-rajz'), ('E', 'Biosz-kémia'), ('F', 'Infó-média')], max_length=1),
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='tagozat4',
            field=models.CharField(blank=True, choices=[('A', 'Olasz'), ('B', 'Angol'), ('C', 'Matek-magyar'), ('D', 'Német-rajz'), ('E', 'Biosz-kémia'), ('F', 'Infó-média')], max_length=1),
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='tagozat5',
            field=models.CharField(blank=True, choices=[('A', 'Olasz'), ('B', 'Angol'), ('C', 'Matek-magyar'), ('D', 'Német-rajz'), ('E', 'Biosz-kémia'), ('F', 'Infó-média')], max_length=1),
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='tagozat6',
            field=models.CharField(blank=True, choices=[('A', 'Olasz'), ('B', 'Angol'), ('C', 'Matek-magyar'), ('D', 'Német-rajz'), ('E', 'Biosz-kémia'), ('F', 'Infó-média')], max_length=1),
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='tagozat7',
            field=models.CharField(blank=True, choices=[('A', 'Olasz'), ('B', 'Angol'), ('C', 'Matek-magyar'), ('D', 'Német-rajz'), ('E', 'Biosz-kémia'), ('F', 'Infó-média')], max_length=1),
        ),
    ]
