# Generated by Django 4.0.3 on 2022-03-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('felvetel', '0004_rename_tagozat_jelentkezo_tagozat1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jelentkezo',
            name='tagozat7',
        ),
    ]
