# Generated by Django 4.0.3 on 2022-03-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felvetel', '0005_remove_jelentkezo_tagozat7'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagozat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=15, verbose_name='név')),
                ('rov', models.CharField(max_length=1, verbose_name='betű')),
            ],
            options={
                'verbose_name': 'Tagozat',
                'verbose_name_plural': 'Tagozatok',
            },
        ),
        migrations.RemoveField(
            model_name='jelentkezo',
            name='felveve',
        ),
        migrations.RemoveField(
            model_name='jelentkezo',
            name='pont',
        ),
        migrations.RemoveField(
            model_name='jelentkezo',
            name='tagozat1',
        ),
        migrations.RemoveField(
            model_name='jelentkezo',
            name='tagozat2',
        ),
        migrations.RemoveField(
            model_name='jelentkezo',
            name='tagozat3',
        ),
        migrations.RemoveField(
            model_name='jelentkezo',
            name='tagozat4',
        ),
        migrations.RemoveField(
            model_name='jelentkezo',
            name='tagozat5',
        ),
        migrations.RemoveField(
            model_name='jelentkezo',
            name='tagozat6',
        ),
        migrations.AlterField(
            model_name='jelentkezo',
            name='azonosito',
            field=models.CharField(max_length=11, verbose_name='azonosító'),
        ),
        migrations.AlterField(
            model_name='jelentkezo',
            name='nev',
            field=models.CharField(max_length=255, verbose_name='név'),
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='tagozatok',
            field=models.ManyToManyField(to='felvetel.tagozat'),
        ),
    ]
