# Generated by Django 4.0.3 on 2022-03-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felvetel', '0006_tagozat_remove_jelentkezo_felveve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jelentkezo',
            name='felveve',
            field=models.ManyToManyField(related_name='felveve+', to='felvetel.tagozat'),
        ),
    ]
