# Generated by Django 4.0.3 on 2022-03-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felvetel', '0007_jelentkezo_felveve'),
    ]

    operations = [
        migrations.AddField(
            model_name='jelentkezo',
            name='A',
            field=models.IntegerField(blank=True, default=0, verbose_name='pontszám (A)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='B',
            field=models.IntegerField(blank=True, default=0, verbose_name='pontszám (B)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='C',
            field=models.IntegerField(blank=True, default=0, verbose_name='pontszám (C)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='D',
            field=models.IntegerField(blank=True, default=0, verbose_name='pontszám (D)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='E',
            field=models.IntegerField(blank=True, default=0, verbose_name='pontszám (E)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='F',
            field=models.IntegerField(blank=True, default=0, verbose_name='pontszám (F)'),
            preserve_default=False,
        ),
    ]
