# Generated by Django 4.0.3 on 2022-03-27 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('felvetel', '0008_jelentkezo_a_jelentkezo_b_jelentkezo_c_jelentkezo_d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagEr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pont', models.IntegerField()),
                ('felveve', models.BooleanField()),
                ('tagozat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felvetel.tagozat')),
            ],
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='tagozat',
            field=models.ManyToManyField(to='felvetel.tager'),
        ),
    ]
