# Generated by Django 4.0.3 on 2022-03-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felvetel', '0010_remove_jelentkezo_tagozat_delete_tager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jelentkezo',
            name='A',
            field=models.FloatField(blank=True, verbose_name='pontszám (A)'),
        ),
        migrations.AlterField(
            model_name='jelentkezo',
            name='B',
            field=models.FloatField(blank=True, verbose_name='pontszám (B)'),
        ),
        migrations.AlterField(
            model_name='jelentkezo',
            name='C',
            field=models.FloatField(blank=True, verbose_name='pontszám (C)'),
        ),
        migrations.AlterField(
            model_name='jelentkezo',
            name='D',
            field=models.FloatField(blank=True, verbose_name='pontszám (D)'),
        ),
        migrations.AlterField(
            model_name='jelentkezo',
            name='E',
            field=models.FloatField(blank=True, verbose_name='pontszám (E)'),
        ),
        migrations.AlterField(
            model_name='jelentkezo',
            name='F',
            field=models.FloatField(blank=True, verbose_name='pontszám (F)'),
        ),
        migrations.AlterField(
            model_name='tagozat',
            name='rov',
            field=models.CharField(max_length=2, verbose_name='betű'),
        ),
    ]
