# Generated by Django 4.0.3 on 2022-03-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felvetel', '0011_alter_jelentkezo_a_alter_jelentkezo_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jelentkezo',
            name='C',
        ),
        migrations.RemoveField(
            model_name='jelentkezo',
            name='D',
        ),
        migrations.RemoveField(
            model_name='jelentkezo',
            name='F',
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='C1',
            field=models.FloatField(blank=True, default=0, verbose_name='pontszám (C1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='C2',
            field=models.FloatField(blank=True, default=0, verbose_name='pontszám (C2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='D1',
            field=models.FloatField(blank=True, default=0, verbose_name='pontszám (D1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='D2',
            field=models.FloatField(blank=True, default=0, verbose_name='pontszám (D2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='F1',
            field=models.FloatField(blank=True, default=0, verbose_name='pontszám (F1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jelentkezo',
            name='F2',
            field=models.FloatField(blank=True, default=0, verbose_name='pontszám (F2)'),
            preserve_default=False,
        ),
    ]
